### ISSUE TITLE
5.3.11  onBeforeEventChanged  Bug

### ISSUE THREAD

**Issue by ibeeger** [DHTMLX/vue-scheduler-demo#9]
In this version, the event is not triggered

5.3.11
```
 scheduler.attachEvent("onBeforeEventChanged", (id, ev) => {
          console.log('onBeforeEventChanged')
        });

```

**Comment by kontyente** [comment]
The same on my side, still no fix after 3 months... has this been abandon?

**Comment by ArtiBorisevich** [comment]
I tried to reproduce the issue using the snippet tool with the latest Scheduler version (now it is v.5.3.13), and it works fine for me: http://snippet.dhtmlx.com/5/c665da9a1
Please try either to update the Scheduler version in your project or update the code of the snippet to replicate the issue and share the new link with us.
